# data.py

KANJI_LIST = [
    {"kanji": "凝視", "read": "ぎょうし"},
    {"kanji": "冷凍", "read": "れいとう"},
    {"kanji": "勘当", "read": "かんどう"},
    {"kanji": "応募", "read": "おうぼ"},
    {"kanji": "励行", "read": "れいこう"},
    {"kanji": "食卓", "read": "しょくたく"},
    {"kanji": "卑屈", "read": "ひくつ"},
    {"kanji": "卸商", "read": "おろししょう"},
    {"kanji": "無双", "read": "むそう"},
    {"kanji": "又貸し", "read": "またがし"},
    {"kanji": "哀願", "read": "あいがん"},
    {"kanji": "吉報", "read": "きっぽう"},
    {"kanji": "啓示", "read": "けいじ"},
    {"kanji": "哲学", "read": "てつがく"},
    {"kanji": "能吏", "read": "のうり"},
    {"kanji": "開墾", "read": "かいこん"},
    {"kanji": "失墜", "read": "しっつい"},
    {"kanji": "塗料", "read": "とりょう"},
    {"kanji": "墨絵", "read": "すみえ"},
    {"kanji": "契機", "read": "けいき"},
    {"kanji": "争奪", "read": "そうだつ"},
    {"kanji": "奉仕", "read": "ほうし"},
    {"kanji": "老婆", "read": "ろうば"},
    {"kanji": "寿命", "read": "じゅみょう"},
    {"kanji": "封建的", "read": "ほうけんてき"},
    {"kanji": "岳父", "read": "がくふ"},
    {"kanji": "崩落", "read": "ほうらく"},
    {"kanji": "帝国", "read": "ていこく"},
    {"kanji": "幻滅", "read": "げんめつ"},
    {"kanji": "幽境", "read": "ゆうきょう"},
    {"kanji": "慰労会", "read": "いろうかい"},
    {"kanji": "忌中", "read": "きちゅう"},
    {"kanji": "愚鈍", "read": "ぐどん"},
    {"kanji": "小憩", "read": "しょうけい"},
    {"kanji": "慈善", "read": "じぜん"},
    {"kanji": "凝らす", "read": "こらす"},
    {"kanji": "奪う", "read": "うばう"},
    {"kanji": "慰める", "read": "なぐさめる"} 
]
